// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package container

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockContainerCLI creates a new instance of MockContainerCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainerCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainerCLI {
	mock := &MockContainerCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContainerCLI is an autogenerated mock type for the ContainerCLI type
type MockContainerCLI struct {
	mock.Mock
}

type MockContainerCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainerCLI) EXPECT() *MockContainerCLI_Expecter {
	return &MockContainerCLI_Expecter{mock: &_m.Mock}
}

// CleanResources provides a mock function for the type MockContainerCLI
func (_mock *MockContainerCLI) CleanResources() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CleanResources")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerCLI_CleanResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanResources'
type MockContainerCLI_CleanResources_Call struct {
	*mock.Call
}

// CleanResources is a helper method to define mock.On call
func (_e *MockContainerCLI_Expecter) CleanResources() *MockContainerCLI_CleanResources_Call {
	return &MockContainerCLI_CleanResources_Call{Call: _e.mock.On("CleanResources")}
}

func (_c *MockContainerCLI_CleanResources_Call) Run(run func()) *MockContainerCLI_CleanResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainerCLI_CleanResources_Call) Return(err error) *MockContainerCLI_CleanResources_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerCLI_CleanResources_Call) RunAndReturn(run func() error) *MockContainerCLI_CleanResources_Call {
	_c.Call.Return(run)
	return _c
}

// DownContainer provides a mock function for the type MockContainerCLI
func (_mock *MockContainerCLI) DownContainer(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for DownContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerCLI_DownContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownContainer'
type MockContainerCLI_DownContainer_Call struct {
	*mock.Call
}

// DownContainer is a helper method to define mock.On call
//   - path string
func (_e *MockContainerCLI_Expecter) DownContainer(path interface{}) *MockContainerCLI_DownContainer_Call {
	return &MockContainerCLI_DownContainer_Call{Call: _e.mock.On("DownContainer", path)}
}

func (_c *MockContainerCLI_DownContainer_Call) Run(run func(path string)) *MockContainerCLI_DownContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerCLI_DownContainer_Call) Return(err error) *MockContainerCLI_DownContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerCLI_DownContainer_Call) RunAndReturn(run func(path string) error) *MockContainerCLI_DownContainer_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRelatedContainers provides a mock function for the type MockContainerCLI
func (_mock *MockContainerCLI) GetAllRelatedContainers(path string) ([]string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRelatedContainers")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerCLI_GetAllRelatedContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRelatedContainers'
type MockContainerCLI_GetAllRelatedContainers_Call struct {
	*mock.Call
}

// GetAllRelatedContainers is a helper method to define mock.On call
//   - path string
func (_e *MockContainerCLI_Expecter) GetAllRelatedContainers(path interface{}) *MockContainerCLI_GetAllRelatedContainers_Call {
	return &MockContainerCLI_GetAllRelatedContainers_Call{Call: _e.mock.On("GetAllRelatedContainers", path)}
}

func (_c *MockContainerCLI_GetAllRelatedContainers_Call) Run(run func(path string)) *MockContainerCLI_GetAllRelatedContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerCLI_GetAllRelatedContainers_Call) Return(strings []string, err error) *MockContainerCLI_GetAllRelatedContainers_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockContainerCLI_GetAllRelatedContainers_Call) RunAndReturn(run func(path string) ([]string, error)) *MockContainerCLI_GetAllRelatedContainers_Call {
	_c.Call.Return(run)
	return _c
}

// KillContainer provides a mock function for the type MockContainerCLI
func (_mock *MockContainerCLI) KillContainer(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for KillContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerCLI_KillContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillContainer'
type MockContainerCLI_KillContainer_Call struct {
	*mock.Call
}

// KillContainer is a helper method to define mock.On call
//   - path string
func (_e *MockContainerCLI_Expecter) KillContainer(path interface{}) *MockContainerCLI_KillContainer_Call {
	return &MockContainerCLI_KillContainer_Call{Call: _e.mock.On("KillContainer", path)}
}

func (_c *MockContainerCLI_KillContainer_Call) Run(run func(path string)) *MockContainerCLI_KillContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerCLI_KillContainer_Call) Return(err error) *MockContainerCLI_KillContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerCLI_KillContainer_Call) RunAndReturn(run func(path string) error) *MockContainerCLI_KillContainer_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainersOfActiveDevcontainers provides a mock function for the type MockContainerCLI
func (_mock *MockContainerCLI) ListContainersOfActiveDevcontainers() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListContainersOfActiveDevcontainers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerCLI_ListContainersOfActiveDevcontainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainersOfActiveDevcontainers'
type MockContainerCLI_ListContainersOfActiveDevcontainers_Call struct {
	*mock.Call
}

// ListContainersOfActiveDevcontainers is a helper method to define mock.On call
func (_e *MockContainerCLI_Expecter) ListContainersOfActiveDevcontainers() *MockContainerCLI_ListContainersOfActiveDevcontainers_Call {
	return &MockContainerCLI_ListContainersOfActiveDevcontainers_Call{Call: _e.mock.On("ListContainersOfActiveDevcontainers")}
}

func (_c *MockContainerCLI_ListContainersOfActiveDevcontainers_Call) Run(run func()) *MockContainerCLI_ListContainersOfActiveDevcontainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainerCLI_ListContainersOfActiveDevcontainers_Call) Return(err error) *MockContainerCLI_ListContainersOfActiveDevcontainers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerCLI_ListContainersOfActiveDevcontainers_Call) RunAndReturn(run func() error) *MockContainerCLI_ListContainersOfActiveDevcontainers_Call {
	_c.Call.Return(run)
	return _c
}

// ListPorts provides a mock function for the type MockContainerCLI
func (_mock *MockContainerCLI) ListPorts(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ListPorts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerCLI_ListPorts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPorts'
type MockContainerCLI_ListPorts_Call struct {
	*mock.Call
}

// ListPorts is a helper method to define mock.On call
//   - path string
func (_e *MockContainerCLI_Expecter) ListPorts(path interface{}) *MockContainerCLI_ListPorts_Call {
	return &MockContainerCLI_ListPorts_Call{Call: _e.mock.On("ListPorts", path)}
}

func (_c *MockContainerCLI_ListPorts_Call) Run(run func(path string)) *MockContainerCLI_ListPorts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerCLI_ListPorts_Call) Return(err error) *MockContainerCLI_ListPorts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerCLI_ListPorts_Call) RunAndReturn(run func(path string) error) *MockContainerCLI_ListPorts_Call {
	_c.Call.Return(run)
	return _c
}

// ShowLogs provides a mock function for the type MockContainerCLI
func (_mock *MockContainerCLI) ShowLogs(path string, follow bool) error {
	ret := _mock.Called(path, follow)

	if len(ret) == 0 {
		panic("no return value specified for ShowLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = returnFunc(path, follow)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerCLI_ShowLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowLogs'
type MockContainerCLI_ShowLogs_Call struct {
	*mock.Call
}

// ShowLogs is a helper method to define mock.On call
//   - path string
//   - follow bool
func (_e *MockContainerCLI_Expecter) ShowLogs(path interface{}, follow interface{}) *MockContainerCLI_ShowLogs_Call {
	return &MockContainerCLI_ShowLogs_Call{Call: _e.mock.On("ShowLogs", path, follow)}
}

func (_c *MockContainerCLI_ShowLogs_Call) Run(run func(path string, follow bool)) *MockContainerCLI_ShowLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerCLI_ShowLogs_Call) Return(err error) *MockContainerCLI_ShowLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerCLI_ShowLogs_Call) RunAndReturn(run func(path string, follow bool) error) *MockContainerCLI_ShowLogs_Call {
	_c.Call.Return(run)
	return _c
}
