// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logger

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Debug(format interface{}, args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(format string, args ...any)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Error(format interface{}, args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(format string, args ...any)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// GetWriter provides a mock function for the type MockLogger
func (_mock *MockLogger) GetWriter() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWriter")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockLogger_GetWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWriter'
type MockLogger_GetWriter_Call struct {
	*mock.Call
}

// GetWriter is a helper method to define mock.On call
func (_e *MockLogger_Expecter) GetWriter() *MockLogger_GetWriter_Call {
	return &MockLogger_GetWriter_Call{Call: _e.mock.On("GetWriter")}
}

func (_c *MockLogger_GetWriter_Call) Run(run func()) *MockLogger_GetWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_GetWriter_Call) Return(writer io.Writer) *MockLogger_GetWriter_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockLogger_GetWriter_Call) RunAndReturn(run func() io.Writer) *MockLogger_GetWriter_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Info(format interface{}, args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(format string, args ...any)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// SetOutput provides a mock function for the type MockLogger
func (_mock *MockLogger) SetOutput(w io.Writer) {
	_mock.Called(w)
	return
}

// MockLogger_SetOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOutput'
type MockLogger_SetOutput_Call struct {
	*mock.Call
}

// SetOutput is a helper method to define mock.On call
//   - w io.Writer
func (_e *MockLogger_Expecter) SetOutput(w interface{}) *MockLogger_SetOutput_Call {
	return &MockLogger_SetOutput_Call{Call: _e.mock.On("SetOutput", w)}
}

func (_c *MockLogger_SetOutput_Call) Run(run func(w io.Writer)) *MockLogger_SetOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_SetOutput_Call) Return() *MockLogger_SetOutput_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_SetOutput_Call) RunAndReturn(run func(w io.Writer)) *MockLogger_SetOutput_Call {
	_c.Run(run)
	return _c
}

// SetVerbose provides a mock function for the type MockLogger
func (_mock *MockLogger) SetVerbose(v bool) {
	_mock.Called(v)
	return
}

// MockLogger_SetVerbose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVerbose'
type MockLogger_SetVerbose_Call struct {
	*mock.Call
}

// SetVerbose is a helper method to define mock.On call
//   - v bool
func (_e *MockLogger_Expecter) SetVerbose(v interface{}) *MockLogger_SetVerbose_Call {
	return &MockLogger_SetVerbose_Call{Call: _e.mock.On("SetVerbose", v)}
}

func (_c *MockLogger_SetVerbose_Call) Run(run func(v bool)) *MockLogger_SetVerbose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_SetVerbose_Call) Return() *MockLogger_SetVerbose_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_SetVerbose_Call) RunAndReturn(run func(v bool)) *MockLogger_SetVerbose_Call {
	_c.Run(run)
	return _c
}

// Success provides a mock function for the type MockLogger
func (_mock *MockLogger) Success(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Success_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Success'
type MockLogger_Success_Call struct {
	*mock.Call
}

// Success is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Success(format interface{}, args ...interface{}) *MockLogger_Success_Call {
	return &MockLogger_Success_Call{Call: _e.mock.On("Success",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Success_Call) Run(run func(format string, args ...any)) *MockLogger_Success_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Success_Call) Return() *MockLogger_Success_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Success_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Success_Call {
	_c.Run(run)
	return _c
}

// Verbose provides a mock function for the type MockLogger
func (_mock *MockLogger) Verbose(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Verbose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verbose'
type MockLogger_Verbose_Call struct {
	*mock.Call
}

// Verbose is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Verbose(format interface{}, args ...interface{}) *MockLogger_Verbose_Call {
	return &MockLogger_Verbose_Call{Call: _e.mock.On("Verbose",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Verbose_Call) Run(run func(format string, args ...any)) *MockLogger_Verbose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Verbose_Call) Return() *MockLogger_Verbose_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Verbose_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Verbose_Call {
	_c.Run(run)
	return _c
}

// VerboseFromOutput provides a mock function for the type MockLogger
func (_mock *MockLogger) VerboseFromOutput(output io.Reader) {
	_mock.Called(output)
	return
}

// MockLogger_VerboseFromOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerboseFromOutput'
type MockLogger_VerboseFromOutput_Call struct {
	*mock.Call
}

// VerboseFromOutput is a helper method to define mock.On call
//   - output io.Reader
func (_e *MockLogger_Expecter) VerboseFromOutput(output interface{}) *MockLogger_VerboseFromOutput_Call {
	return &MockLogger_VerboseFromOutput_Call{Call: _e.mock.On("VerboseFromOutput", output)}
}

func (_c *MockLogger_VerboseFromOutput_Call) Run(run func(output io.Reader)) *MockLogger_VerboseFromOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_VerboseFromOutput_Call) Return() *MockLogger_VerboseFromOutput_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_VerboseFromOutput_Call) RunAndReturn(run func(output io.Reader)) *MockLogger_VerboseFromOutput_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Warn(format interface{}, args ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(format string, args ...any)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}
