// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exec

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// CombinedOutput provides a mock function for the type MockExecutor
func (_mock *MockExecutor) CombinedOutput(name string, args ...string) (string, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(name, args)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CombinedOutput")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) (string, error)); ok {
		return returnFunc(name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...string) string); ok {
		r0 = returnFunc(name, args...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = returnFunc(name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_CombinedOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CombinedOutput'
type MockExecutor_CombinedOutput_Call struct {
	*mock.Call
}

// CombinedOutput is a helper method to define mock.On call
//   - name string
//   - args ...string
func (_e *MockExecutor_Expecter) CombinedOutput(name interface{}, args ...interface{}) *MockExecutor_CombinedOutput_Call {
	return &MockExecutor_CombinedOutput_Call{Call: _e.mock.On("CombinedOutput",
		append([]interface{}{name}, args...)...)}
}

func (_c *MockExecutor_CombinedOutput_Call) Run(run func(name string, args ...string)) *MockExecutor_CombinedOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockExecutor_CombinedOutput_Call) Return(s string, err error) *MockExecutor_CombinedOutput_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockExecutor_CombinedOutput_Call) RunAndReturn(run func(name string, args ...string) (string, error)) *MockExecutor_CombinedOutput_Call {
	_c.Call.Return(run)
	return _c
}

// Output provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Output(name string, args ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(name, args)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) ([]byte, error)); ok {
		return returnFunc(name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...string) []byte); ok {
		r0 = returnFunc(name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = returnFunc(name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type MockExecutor_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
//   - name string
//   - args ...string
func (_e *MockExecutor_Expecter) Output(name interface{}, args ...interface{}) *MockExecutor_Output_Call {
	return &MockExecutor_Output_Call{Call: _e.mock.On("Output",
		append([]interface{}{name}, args...)...)}
}

func (_c *MockExecutor_Output_Call) Run(run func(name string, args ...string)) *MockExecutor_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockExecutor_Output_Call) Return(bytes []byte, err error) *MockExecutor_Output_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockExecutor_Output_Call) RunAndReturn(run func(name string, args ...string) ([]byte, error)) *MockExecutor_Output_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Run(name string, args ...string) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(name, args)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = returnFunc(name, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockExecutor_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - name string
//   - args ...string
func (_e *MockExecutor_Expecter) Run(name interface{}, args ...interface{}) *MockExecutor_Run_Call {
	return &MockExecutor_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{name}, args...)...)}
}

func (_c *MockExecutor_Run_Call) Run(run func(name string, args ...string)) *MockExecutor_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockExecutor_Run_Call) Return(err error) *MockExecutor_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_Run_Call) RunAndReturn(run func(name string, args ...string) error) *MockExecutor_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunDetached provides a mock function for the type MockExecutor
func (_mock *MockExecutor) RunDetached(name string, args ...string) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(name, args)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RunDetached")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = returnFunc(name, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_RunDetached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunDetached'
type MockExecutor_RunDetached_Call struct {
	*mock.Call
}

// RunDetached is a helper method to define mock.On call
//   - name string
//   - args ...string
func (_e *MockExecutor_Expecter) RunDetached(name interface{}, args ...interface{}) *MockExecutor_RunDetached_Call {
	return &MockExecutor_RunDetached_Call{Call: _e.mock.On("RunDetached",
		append([]interface{}{name}, args...)...)}
}

func (_c *MockExecutor_RunDetached_Call) Run(run func(name string, args ...string)) *MockExecutor_RunDetached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockExecutor_RunDetached_Call) Return(err error) *MockExecutor_RunDetached_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_RunDetached_Call) RunAndReturn(run func(name string, args ...string) error) *MockExecutor_RunDetached_Call {
	_c.Call.Return(run)
	return _c
}

// RunInteractive provides a mock function for the type MockExecutor
func (_mock *MockExecutor) RunInteractive(name string, args ...string) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(name, args)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RunInteractive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = returnFunc(name, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_RunInteractive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInteractive'
type MockExecutor_RunInteractive_Call struct {
	*mock.Call
}

// RunInteractive is a helper method to define mock.On call
//   - name string
//   - args ...string
func (_e *MockExecutor_Expecter) RunInteractive(name interface{}, args ...interface{}) *MockExecutor_RunInteractive_Call {
	return &MockExecutor_RunInteractive_Call{Call: _e.mock.On("RunInteractive",
		append([]interface{}{name}, args...)...)}
}

func (_c *MockExecutor_RunInteractive_Call) Run(run func(name string, args ...string)) *MockExecutor_RunInteractive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockExecutor_RunInteractive_Call) Return(err error) *MockExecutor_RunInteractive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_RunInteractive_Call) RunAndReturn(run func(name string, args ...string) error) *MockExecutor_RunInteractive_Call {
	_c.Call.Return(run)
	return _c
}

// RunWithOutput provides a mock function for the type MockExecutor
func (_mock *MockExecutor) RunWithOutput(output io.Writer, name string, args ...string) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(output, name, args)
	} else {
		tmpRet = _mock.Called(output, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RunWithOutput")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer, string, ...string) error); ok {
		r0 = returnFunc(output, name, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_RunWithOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunWithOutput'
type MockExecutor_RunWithOutput_Call struct {
	*mock.Call
}

// RunWithOutput is a helper method to define mock.On call
//   - output io.Writer
//   - name string
//   - args ...string
func (_e *MockExecutor_Expecter) RunWithOutput(output interface{}, name interface{}, args ...interface{}) *MockExecutor_RunWithOutput_Call {
	return &MockExecutor_RunWithOutput_Call{Call: _e.mock.On("RunWithOutput",
		append([]interface{}{output, name}, args...)...)}
}

func (_c *MockExecutor_RunWithOutput_Call) Run(run func(output io.Writer, name string, args ...string)) *MockExecutor_RunWithOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockExecutor_RunWithOutput_Call) Return(err error) *MockExecutor_RunWithOutput_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_RunWithOutput_Call) RunAndReturn(run func(output io.Writer, name string, args ...string) error) *MockExecutor_RunWithOutput_Call {
	_c.Call.Return(run)
	return _c
}
