// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package devcontainer

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDevContainerCLI creates a new instance of MockDevContainerCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDevContainerCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDevContainerCLI {
	mock := &MockDevContainerCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDevContainerCLI is an autogenerated mock type for the DevContainerCLI type
type MockDevContainerCLI struct {
	mock.Mock
}

type MockDevContainerCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDevContainerCLI) EXPECT() *MockDevContainerCLI_Expecter {
	return &MockDevContainerCLI_Expecter{mock: &_m.Mock}
}

// GetWorkspaceFolder provides a mock function for the type MockDevContainerCLI
func (_mock *MockDevContainerCLI) GetWorkspaceFolder(absPath string) (string, error) {
	ret := _mock.Called(absPath)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceFolder")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(absPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(absPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(absPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDevContainerCLI_GetWorkspaceFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspaceFolder'
type MockDevContainerCLI_GetWorkspaceFolder_Call struct {
	*mock.Call
}

// GetWorkspaceFolder is a helper method to define mock.On call
//   - absPath string
func (_e *MockDevContainerCLI_Expecter) GetWorkspaceFolder(absPath interface{}) *MockDevContainerCLI_GetWorkspaceFolder_Call {
	return &MockDevContainerCLI_GetWorkspaceFolder_Call{Call: _e.mock.On("GetWorkspaceFolder", absPath)}
}

func (_c *MockDevContainerCLI_GetWorkspaceFolder_Call) Run(run func(absPath string)) *MockDevContainerCLI_GetWorkspaceFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDevContainerCLI_GetWorkspaceFolder_Call) Return(s string, err error) *MockDevContainerCLI_GetWorkspaceFolder_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDevContainerCLI_GetWorkspaceFolder_Call) RunAndReturn(run func(absPath string) (string, error)) *MockDevContainerCLI_GetWorkspaceFolder_Call {
	_c.Call.Return(run)
	return _c
}

// ReadConfiguration provides a mock function for the type MockDevContainerCLI
func (_mock *MockDevContainerCLI) ReadConfiguration(absPath string) (*DevContainerConfiguration, error) {
	ret := _mock.Called(absPath)

	if len(ret) == 0 {
		panic("no return value specified for ReadConfiguration")
	}

	var r0 *DevContainerConfiguration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*DevContainerConfiguration, error)); ok {
		return returnFunc(absPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *DevContainerConfiguration); ok {
		r0 = returnFunc(absPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DevContainerConfiguration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(absPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDevContainerCLI_ReadConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadConfiguration'
type MockDevContainerCLI_ReadConfiguration_Call struct {
	*mock.Call
}

// ReadConfiguration is a helper method to define mock.On call
//   - absPath string
func (_e *MockDevContainerCLI_Expecter) ReadConfiguration(absPath interface{}) *MockDevContainerCLI_ReadConfiguration_Call {
	return &MockDevContainerCLI_ReadConfiguration_Call{Call: _e.mock.On("ReadConfiguration", absPath)}
}

func (_c *MockDevContainerCLI_ReadConfiguration_Call) Run(run func(absPath string)) *MockDevContainerCLI_ReadConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDevContainerCLI_ReadConfiguration_Call) Return(devContainerConfiguration *DevContainerConfiguration, err error) *MockDevContainerCLI_ReadConfiguration_Call {
	_c.Call.Return(devContainerConfiguration, err)
	return _c
}

func (_c *MockDevContainerCLI_ReadConfiguration_Call) RunAndReturn(run func(absPath string) (*DevContainerConfiguration, error)) *MockDevContainerCLI_ReadConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type MockDevContainerCLI
func (_mock *MockDevContainerCLI) Up(workspace string) error {
	ret := _mock.Called(workspace)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(workspace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDevContainerCLI_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockDevContainerCLI_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - workspace string
func (_e *MockDevContainerCLI_Expecter) Up(workspace interface{}) *MockDevContainerCLI_Up_Call {
	return &MockDevContainerCLI_Up_Call{Call: _e.mock.On("Up", workspace)}
}

func (_c *MockDevContainerCLI_Up_Call) Run(run func(workspace string)) *MockDevContainerCLI_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDevContainerCLI_Up_Call) Return(err error) *MockDevContainerCLI_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDevContainerCLI_Up_Call) RunAndReturn(run func(workspace string) error) *MockDevContainerCLI_Up_Call {
	_c.Call.Return(run)
	return _c
}
