// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pather

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPather creates a new instance of MockPather. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPather(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPather {
	mock := &MockPather{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPather is an autogenerated mock type for the Pather type
type MockPather struct {
	mock.Mock
}

type MockPather_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPather) EXPECT() *MockPather_Expecter {
	return &MockPather_Expecter{mock: &_m.Mock}
}

// GetAbsPath provides a mock function for the type MockPather
func (_mock *MockPather) GetAbsPath(target string) (string, error) {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for GetAbsPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(target)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPather_GetAbsPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAbsPath'
type MockPather_GetAbsPath_Call struct {
	*mock.Call
}

// GetAbsPath is a helper method to define mock.On call
//   - target string
func (_e *MockPather_Expecter) GetAbsPath(target interface{}) *MockPather_GetAbsPath_Call {
	return &MockPather_GetAbsPath_Call{Call: _e.mock.On("GetAbsPath", target)}
}

func (_c *MockPather_GetAbsPath_Call) Run(run func(target string)) *MockPather_GetAbsPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPather_GetAbsPath_Call) Return(s string, err error) *MockPather_GetAbsPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPather_GetAbsPath_Call) RunAndReturn(run func(target string) (string, error)) *MockPather_GetAbsPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetPathFromArgs provides a mock function for the type MockPather
func (_mock *MockPather) GetPathFromArgs(args []string) string {
	ret := _mock.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for GetPathFromArgs")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]string) string); ok {
		r0 = returnFunc(args)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPather_GetPathFromArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPathFromArgs'
type MockPather_GetPathFromArgs_Call struct {
	*mock.Call
}

// GetPathFromArgs is a helper method to define mock.On call
//   - args []string
func (_e *MockPather_Expecter) GetPathFromArgs(args interface{}) *MockPather_GetPathFromArgs_Call {
	return &MockPather_GetPathFromArgs_Call{Call: _e.mock.On("GetPathFromArgs", args)}
}

func (_c *MockPather_GetPathFromArgs_Call) Run(run func(args []string)) *MockPather_GetPathFromArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPather_GetPathFromArgs_Call) Return(s string) *MockPather_GetPathFromArgs_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPather_GetPathFromArgs_Call) RunAndReturn(run func(args []string) string) *MockPather_GetPathFromArgs_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealPath provides a mock function for the type MockPather
func (_mock *MockPather) GetRealPath(absPath string) (string, error) {
	ret := _mock.Called(absPath)

	if len(ret) == 0 {
		panic("no return value specified for GetRealPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(absPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(absPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(absPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPather_GetRealPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealPath'
type MockPather_GetRealPath_Call struct {
	*mock.Call
}

// GetRealPath is a helper method to define mock.On call
//   - absPath string
func (_e *MockPather_Expecter) GetRealPath(absPath interface{}) *MockPather_GetRealPath_Call {
	return &MockPather_GetRealPath_Call{Call: _e.mock.On("GetRealPath", absPath)}
}

func (_c *MockPather_GetRealPath_Call) Run(run func(absPath string)) *MockPather_GetRealPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPather_GetRealPath_Call) Return(s string, err error) *MockPather_GetRealPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPather_GetRealPath_Call) RunAndReturn(run func(absPath string) (string, error)) *MockPather_GetRealPath_Call {
	_c.Call.Return(run)
	return _c
}
