// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// GetConfigPath provides a mock function for the type MockConfig
func (_mock *MockConfig) GetConfigPath() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfig_GetConfigPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigPath'
type MockConfig_GetConfigPath_Call struct {
	*mock.Call
}

// GetConfigPath is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetConfigPath() *MockConfig_GetConfigPath_Call {
	return &MockConfig_GetConfigPath_Call{Call: _e.mock.On("GetConfigPath")}
}

func (_c *MockConfig_GetConfigPath_Call) Run(run func()) *MockConfig_GetConfigPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetConfigPath_Call) Return(s string, err error) *MockConfig_GetConfigPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConfig_GetConfigPath_Call) RunAndReturn(run func() (string, error)) *MockConfig_GetConfigPath_Call {
	_c.Call.Return(run)
	return _c
}

// HasConfigFile provides a mock function for the type MockConfig
func (_mock *MockConfig) HasConfigFile() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasConfigFile")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_HasConfigFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasConfigFile'
type MockConfig_HasConfigFile_Call struct {
	*mock.Call
}

// HasConfigFile is a helper method to define mock.On call
func (_e *MockConfig_Expecter) HasConfigFile() *MockConfig_HasConfigFile_Call {
	return &MockConfig_HasConfigFile_Call{Call: _e.mock.On("HasConfigFile")}
}

func (_c *MockConfig_HasConfigFile_Call) Run(run func()) *MockConfig_HasConfigFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_HasConfigFile_Call) Return(b bool) *MockConfig_HasConfigFile_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_HasConfigFile_Call) RunAndReturn(run func() bool) *MockConfig_HasConfigFile_Call {
	_c.Call.Return(run)
	return _c
}

// InterativeSelect provides a mock function for the type MockConfig
func (_mock *MockConfig) InterativeSelect(key string) (string, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for InterativeSelect")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfig_InterativeSelect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InterativeSelect'
type MockConfig_InterativeSelect_Call struct {
	*mock.Call
}

// InterativeSelect is a helper method to define mock.On call
//   - key string
func (_e *MockConfig_Expecter) InterativeSelect(key interface{}) *MockConfig_InterativeSelect_Call {
	return &MockConfig_InterativeSelect_Call{Call: _e.mock.On("InterativeSelect", key)}
}

func (_c *MockConfig_InterativeSelect_Call) Run(run func(key string)) *MockConfig_InterativeSelect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_InterativeSelect_Call) Return(s string, err error) *MockConfig_InterativeSelect_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConfig_InterativeSelect_Call) RunAndReturn(run func(key string) (string, error)) *MockConfig_InterativeSelect_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockConfig
func (_mock *MockConfig) Load() GlobalConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 GlobalConfig
	if returnFunc, ok := ret.Get(0).(func() GlobalConfig); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(GlobalConfig)
	}
	return r0
}

// MockConfig_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockConfig_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockConfig_Expecter) Load() *MockConfig_Load_Call {
	return &MockConfig_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockConfig_Load_Call) Run(run func()) *MockConfig_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_Load_Call) Return(globalConfig GlobalConfig) *MockConfig_Load_Call {
	_c.Call.Return(globalConfig)
	return _c
}

func (_c *MockConfig_Load_Call) RunAndReturn(run func() GlobalConfig) *MockConfig_Load_Call {
	_c.Call.Return(run)
	return _c
}

// LoadByKey provides a mock function for the type MockConfig
func (_mock *MockConfig) LoadByKey(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for LoadByKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_LoadByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadByKey'
type MockConfig_LoadByKey_Call struct {
	*mock.Call
}

// LoadByKey is a helper method to define mock.On call
//   - key string
func (_e *MockConfig_Expecter) LoadByKey(key interface{}) *MockConfig_LoadByKey_Call {
	return &MockConfig_LoadByKey_Call{Call: _e.mock.On("LoadByKey", key)}
}

func (_c *MockConfig_LoadByKey_Call) Run(run func(key string)) *MockConfig_LoadByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_LoadByKey_Call) Return(s string) *MockConfig_LoadByKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_LoadByKey_Call) RunAndReturn(run func(key string) string) *MockConfig_LoadByKey_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockConfig
func (_mock *MockConfig) Save(key string, value string) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockConfig_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockConfig_Expecter) Save(key interface{}, value interface{}) *MockConfig_Save_Call {
	return &MockConfig_Save_Call{Call: _e.mock.On("Save", key, value)}
}

func (_c *MockConfig_Save_Call) Run(run func(key string, value string)) *MockConfig_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfig_Save_Call) Return(err error) *MockConfig_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_Save_Call) RunAndReturn(run func(key string, value string) error) *MockConfig_Save_Call {
	_c.Call.Return(run)
	return _c
}

// TrySave provides a mock function for the type MockConfig
func (_mock *MockConfig) TrySave(key string, value string) (string, error) {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for TrySave")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(key, value)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(key, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfig_TrySave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrySave'
type MockConfig_TrySave_Call struct {
	*mock.Call
}

// TrySave is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockConfig_Expecter) TrySave(key interface{}, value interface{}) *MockConfig_TrySave_Call {
	return &MockConfig_TrySave_Call{Call: _e.mock.On("TrySave", key, value)}
}

func (_c *MockConfig_TrySave_Call) Run(run func(key string, value string)) *MockConfig_TrySave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfig_TrySave_Call) Return(s string, err error) *MockConfig_TrySave_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConfig_TrySave_Call) RunAndReturn(run func(key string, value string) (string, error)) *MockConfig_TrySave_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateKey provides a mock function for the type MockConfig
func (_mock *MockConfig) ValidateKey(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ValidateKey")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_ValidateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateKey'
type MockConfig_ValidateKey_Call struct {
	*mock.Call
}

// ValidateKey is a helper method to define mock.On call
//   - key string
func (_e *MockConfig_Expecter) ValidateKey(key interface{}) *MockConfig_ValidateKey_Call {
	return &MockConfig_ValidateKey_Call{Call: _e.mock.On("ValidateKey", key)}
}

func (_c *MockConfig_ValidateKey_Call) Run(run func(key string)) *MockConfig_ValidateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_ValidateKey_Call) Return(b bool) *MockConfig_ValidateKey_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_ValidateKey_Call) RunAndReturn(run func(key string) bool) *MockConfig_ValidateKey_Call {
	_c.Call.Return(run)
	return _c
}
