// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vscode

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockVSCode creates a new instance of MockVSCode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVSCode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVSCode {
	mock := &MockVSCode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVSCode is an autogenerated mock type for the VSCode type
type MockVSCode struct {
	mock.Mock
}

type MockVSCode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVSCode) EXPECT() *MockVSCode_Expecter {
	return &MockVSCode_Expecter{mock: &_m.Mock}
}

// GetContainerWorkspaceURI provides a mock function for the type MockVSCode
func (_mock *MockVSCode) GetContainerWorkspaceURI(absPath string) (string, error) {
	ret := _mock.Called(absPath)

	if len(ret) == 0 {
		panic("no return value specified for GetContainerWorkspaceURI")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(absPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(absPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(absPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVSCode_GetContainerWorkspaceURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainerWorkspaceURI'
type MockVSCode_GetContainerWorkspaceURI_Call struct {
	*mock.Call
}

// GetContainerWorkspaceURI is a helper method to define mock.On call
//   - absPath string
func (_e *MockVSCode_Expecter) GetContainerWorkspaceURI(absPath interface{}) *MockVSCode_GetContainerWorkspaceURI_Call {
	return &MockVSCode_GetContainerWorkspaceURI_Call{Call: _e.mock.On("GetContainerWorkspaceURI", absPath)}
}

func (_c *MockVSCode_GetContainerWorkspaceURI_Call) Run(run func(absPath string)) *MockVSCode_GetContainerWorkspaceURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVSCode_GetContainerWorkspaceURI_Call) Return(s string, err error) *MockVSCode_GetContainerWorkspaceURI_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockVSCode_GetContainerWorkspaceURI_Call) RunAndReturn(run func(absPath string) (string, error)) *MockVSCode_GetContainerWorkspaceURI_Call {
	_c.Call.Return(run)
	return _c
}

// OpenWorkspaceByURI provides a mock function for the type MockVSCode
func (_mock *MockVSCode) OpenWorkspaceByURI(workspaceURI string) error {
	ret := _mock.Called(workspaceURI)

	if len(ret) == 0 {
		panic("no return value specified for OpenWorkspaceByURI")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(workspaceURI)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVSCode_OpenWorkspaceByURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenWorkspaceByURI'
type MockVSCode_OpenWorkspaceByURI_Call struct {
	*mock.Call
}

// OpenWorkspaceByURI is a helper method to define mock.On call
//   - workspaceURI string
func (_e *MockVSCode_Expecter) OpenWorkspaceByURI(workspaceURI interface{}) *MockVSCode_OpenWorkspaceByURI_Call {
	return &MockVSCode_OpenWorkspaceByURI_Call{Call: _e.mock.On("OpenWorkspaceByURI", workspaceURI)}
}

func (_c *MockVSCode_OpenWorkspaceByURI_Call) Run(run func(workspaceURI string)) *MockVSCode_OpenWorkspaceByURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVSCode_OpenWorkspaceByURI_Call) Return(err error) *MockVSCode_OpenWorkspaceByURI_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVSCode_OpenWorkspaceByURI_Call) RunAndReturn(run func(workspaceURI string) error) *MockVSCode_OpenWorkspaceByURI_Call {
	_c.Call.Return(run)
	return _c
}
