name: Publish Snap

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download snap artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          commit: ${{ github.event.release.tag_name }}
          name: snap-amd64

      - name: Publish amd64 to Snap Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
        with:
          snap: "*.snap"
          release: stable